### PR TITLE
[CP] increase the number of demos per page

### PR DESCRIPTION
**Pull request by kidanger**

### CODE REVIEW

**Comment by mcolom** [comment]
Thanks for the PR! We'll merge it.
Did you test it in local already?

**Comment by kidanger** [comment]
No, I'm assuming that you can do that very easily.

**Comment by mcolom** [comment]
OK, we'll do it this time, but in general you need to check that your PRs actually work, first in your local environment and then in integration. But no problem of course, we can do it. Tomorrow most probably we'll merge in prod.

**Comment by mcolom** [comment]
Could you change the commit message? It says "demoinfo: increase the number of demos per page", but this change isn't affecting demoInfo, only the CP. Change it to "[CP] increase the number of demos per page in the index".
Thanks!

**Pull request merged**
